CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users (id),
    full_name VARCHAR(255),
    avatar_url VARCHAR(255),
    total_score INTEGER,
    level INTEGER,
    current_streak INTEGER
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES categories (id),
    question_text TEXT NOT NULL,
    optiona VARCHAR(255) NOT NULL,
    optionb VARCHAR(255) NOT NULL,
    optionc VARCHAR(255) NOT NULL,
    optiond VARCHAR(255) NOT NULL,
    correct_answer VARCHAR(1) NOT NULL,
    time_limit_seconds INTEGER
);

CREATE TABLE IF NOT EXISTS quiz_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    category_id BIGINT NOT NULL REFERENCES categories (id),
    total_questions INTEGER,
    total_score INTEGER,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    completed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quiz_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES quiz_sessions (id),
    question_id BIGINT NOT NULL REFERENCES questions (id),
    user_ans VARCHAR(255),
    is_correct BOOLEAN,
    time_taken_seconds INTEGER,
    score_earned INTEGER
);

CREATE INDEX IF NOT EXISTS idx_questions_category ON questions (category_id);
CREATE INDEX IF NOT EXISTS idx_quiz_sessions_user ON quiz_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_quiz_details_session ON quiz_details (session_id);
CREATE INDEX IF NOT EXISTS idx_quiz_details_question ON quiz_details (question_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_total_score ON user_profiles (total_score DESC);